### ISSUE TITLE
[Crash]: Crash upon clicking Config button (via game menu mod option mod) while on server

### ISSUE THREAD

**Issue by MrKashew** [Fuzss/forgeconfigscreens#14]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

ForgeConfigScreens-v8.0.0-1.20.1-Forge

### Notes (Required)
Happens on server but not on single player
this mod is on server and client
using this mod as well on clientside
[gamemenumodoption](https://modrinth.com/mod/gamemenumodoption)
![image](https://github.com/Fuzss/forgeconfigscreens/assets/53996665/b5a5fd1f-a94d-43ce-9444-9764bb46edd6)
Server:
[latest.log](https://github.com/Fuzss/forgeconfigscreens/files/12206544/latest.log)
[debug.log](https://github.com/Fuzss/forgeconfigscreens/files/12206543/debug.log)
Client:
[latest.log](https://github.com/Fuzss/forgeconfigscreens/files/12206539/latest.log)
[debug.log](https://github.com/Fuzss/forgeconfigscreens/files/12206540/debug.log)

### Crash Report (Required)

see desc

### latest.log (Optional)

see desc

**Comment by Fuzss** [comment]
Thanks, fixed in v8.0.1. Get in on Modrinth for now, CurseForge takes about 12h atm to approve new versions.
