### ISSUE TITLE
[Bug]: When trying to config a mod you will be send to the World creation screen.

### ISSUE THREAD

**Issue by Linusintro** [Fuzss/forgeconfigscreens#18]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.4

### Mod Version (Required)

6.0.0

### Notes (Required)

When trying to config a mod you will be send to the world creation screen.
It only happens if you haven't created any world yet.
That is because in newer versions of Minecraft you will be send automaticly from world selection sceen to the 
world creation screen if you haven't created any world.

**Comment by Fuzss** [comment]
Thanks for reporting. This is fixed for 1.20.1. 1.19.4 is no longer supported.
