### ISSUE TITLE
[Suggestion]: Keybinds 

### ISSUE THREAD

**Issue by Krimatoria** [Fuzss/forgeconfigscreens#25]
### Suggestion (Required)

I think I need a keybinds that can be assigned to open the settings directly from the game to configure mods. Since this will make the path easier.

Configured - it was here, your faces are similar, it just had a menu button.

![image](https://github.com/Fuzss/forgeconfigscreens/assets/106809386/559e8e65-54d2-4681-958a-083b90d0079a)
![image](https://github.com/Fuzss/forgeconfigscreens/assets/106809386/3327b56a-bddd-4593-b40d-be331195b85d)

**Comment by Fuzss** [comment]
That would be up to the mod list implementation. I think Catalogue and Mod Menu already allow for setting a key which is unbound by default.

**Comment by Krimatoria** [comment]
> That would be up to the mod list implementation. I think Catalogue and Mod Menu already allow for setting a key which is unbound by default.

Not) there is no button associated with your mod.
