### ISSUE TITLE
[Suggestion] Increase character limit for string list fields

### ISSUE THREAD

**Issue by Questwizard** [Fuzss/forgeconfigscreens#4]
There appears to be a 32 character limit for editing string list fields. I'd suggest increasing this to at least 48, even if it leads to horizontal scrolling textboxes occasionally, as some mods need long ids typed out. Some of them I've encountered can be around 35-40 characters at times. I have to close down the game, then edit those entries manually because of the limit. Its no big deal, just a minor inconvenience to have to do it occasionally. This is using 1.2.0 on MC 1.16.5

**Comment by dhasial** [comment]
I'm having the same issue on 3.2.0, MC 1.18.2

**Comment by SeanChengN** [comment]
https://github.com/Mrbysco/Spoiled/issues/35

**Comment by Fuzss** [comment]
Thanks, fixed in v8.0.1. Get in on Modrinth for now, CurseForge takes about 12h atm to approve new versions.
Will backport to 1.18.2 at some point, 1.16 is no longer supported.

**Comment by V972** [comment]
I would like to ask/remind about backporting this to 1.18.2 please, it's been 1.5 years.
