### ISSUE TITLE
mod button no longer shows up

### ISSUE THREAD

**Issue by HoodBlah** [Fuzss/forgeconfigscreens#5]
I am using config menu and usually the mod button shows up so I can edit the configs. But then I got the better mod button mod so that I could change the button orientation. However, the game would crash on loadup with the error that config menu couldn't start. After getting rid of the better mod menu the game starts, but the mods button no longer appears in game and I cant change config.

**Comment by Fuzss** [comment]
You need to give me your crash-report

**Comment by Fuzss** [comment]
No crash-report has been provided. If this issue pops up again please provide a crash-report following these instructions: https://gist.github.com/Fuzss/9692f6ed5e8cca485a58004c28c9045b

For now closing this report.
