### ISSUE TITLE
Add support for json5 format

### ISSUE THREAD

**Issue by RandomGuy91** [Fuzss/forgeconfigscreens#8]
Hi, I love this mod and I use it all the time. But when I install certain mods they don't allow you to copy it to defaults and I find that feature REALLY useful. I was specifically thinking of Serilum mods, but other mods use this format too. Thx!

**Comment by RandomGuy91** [comment]
Btw, I've already spoken with Serilum and he said that he can't do anything about the config format. Obviously, this isn't a bug or anything, just an idea for improvement. :)

**Comment by Fuzss** [comment]
Default configs are a feature specific to Forge's config implementation. Other custom config system generally don't have something like it, so there is no point.
